apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base  # Path to the base directory containing the resources to include in the kustomization.

patches:        # List of patches to apply to the resources in the base directory.
- path: deployment-prd.yaml
- path: service-prd.yaml